//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryInfo
    {
        public int SalarySheetNo { get; set; }
        public int EmpCode { get; set; }
        public decimal Basic { get; set; }
        public decimal Hra { get; set; }
        public decimal Da { get; set; }
    
        public virtual EmpProfile EmpProfile { get; set; }
    }
}
